from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType

CIC_IDS_2017_M_SCHEMA = StructType([
    StructField(" Destination Port", IntegerType(), True),
    StructField(" Flow Duration", DoubleType(), True),
    StructField(" Total Fwd Packets", DoubleType(), True),
    StructField(" Total Backward Packets", DoubleType(), True),
    StructField("Total Length of Fwd Packets", DoubleType(), True),
    StructField(" Total Length of Bwd Packets", DoubleType(), True),
    StructField(" Fwd Packet Length Max", DoubleType(), True),
    StructField(" Fwd Packet Length Min", DoubleType(), True),
    StructField(" Fwd Packet Length Mean", DoubleType(), True),
    StructField(" Fwd Packet Length Std", DoubleType(), True),
    StructField("Bwd Packet Length Max", DoubleType(), True),
    StructField(" Bwd Packet Length Min", DoubleType(), True),
    StructField(" Bwd Packet Length Mean", DoubleType(), True),
    StructField(" Bwd Packet Length Std", DoubleType(), True),
    StructField("Flow Bytes/s", DoubleType(), True),
    StructField(" Flow Packets/s", DoubleType(), True),
    StructField(" Flow IAT Mean", DoubleType(), True),
    StructField(" Flow IAT Std", DoubleType(), True),
    StructField(" Flow IAT Max", DoubleType(), True),
    StructField(" Flow IAT Min", DoubleType(), True),
    StructField("Fwd IAT Total", DoubleType(), True),
    StructField(" Fwd IAT Mean", DoubleType(), True),
    StructField(" Fwd IAT Std", DoubleType(), True),
    StructField(" Fwd IAT Max", DoubleType(), True),
    StructField(" Fwd IAT Min", DoubleType(), True),
    StructField("Bwd IAT Total", DoubleType(), True),
    StructField(" Bwd IAT Mean", DoubleType(), True),
    StructField(" Bwd IAT Std", DoubleType(), True),
    StructField(" Bwd IAT Max", DoubleType(), True),
    StructField(" Bwd IAT Min", DoubleType(), True),
    StructField("Fwd PSH Flags", DoubleType(), True),
    StructField(" Bwd PSH Flags", DoubleType(), True),
    StructField(" Fwd URG Flags", DoubleType(), True),
    StructField(" Bwd URG Flags", DoubleType(), True),
    StructField(" Fwd Header Length", DoubleType(), True),
    StructField(" Bwd Header Length", DoubleType(), True),
    StructField("Fwd Packets/s", DoubleType(), True),
    StructField(" Bwd Packets/s", DoubleType(), True),
    StructField(" Min Packet Length", DoubleType(), True),
    StructField(" Max Packet Length", DoubleType(), True),
    StructField(" Packet Length Mean", DoubleType(), True),
    StructField(" Packet Length Std", DoubleType(), True),
    StructField(" Packet Length Variance", DoubleType(), True),
    StructField("FIN Flag Count", DoubleType(), True),
    StructField(" SYN Flag Count", DoubleType(), True),
    StructField(" RST Flag Count", DoubleType(), True),
    StructField(" PSH Flag Count", DoubleType(), True),
    StructField(" ACK Flag Count", DoubleType(), True),
    StructField(" URG Flag Count", DoubleType(), True),
    StructField(" CWE Flag Count", DoubleType(), True),
    StructField(" ECE Flag Count", DoubleType(), True),
    StructField(" Down/Up Ratio", DoubleType(), True),
    StructField(" Average Packet Size", DoubleType(), True),
    StructField(" Avg Fwd Segment Size", DoubleType(), True),
    StructField(" Avg Bwd Segment Size", DoubleType(), True),
    StructField(" Fwd Header Length.1", DoubleType(), True),
    StructField("Fwd Avg Bytes/Bulk", DoubleType(), True),
    StructField(" Fwd Avg Packets/Bulk", DoubleType(), True),
    StructField(" Fwd Avg Bulk Rate", DoubleType(), True),
    StructField(" Bwd Avg Bytes/Bulk", DoubleType(), True),
    StructField(" Bwd Avg Packets/Bulk", DoubleType(), True),
    StructField("Bwd Avg Bulk Rate", DoubleType(), True),
    StructField("Subflow Fwd Packets", DoubleType(), True),
    StructField(" Subflow Fwd Bytes", DoubleType(), True),
    StructField(" Subflow Bwd Packets", DoubleType(), True),
    StructField(" Subflow Bwd Bytes", DoubleType(), True),
    StructField("Init_Win_bytes_forward", DoubleType(), True),
    StructField(" Init_Win_bytes_backward", DoubleType(), True),
    StructField(" act_data_pkt_fwd", DoubleType(), True),
    StructField(" min_seg_size_forward", DoubleType(), True),
    StructField("Active Mean", DoubleType(), True),
    StructField(" Active Std", DoubleType(), True),
    StructField(" Active Max", DoubleType(), True),
    StructField(" Active Min", DoubleType(), True),
    StructField("Idle Mean", DoubleType(), True),
    StructField(" Idle Std", DoubleType(), True),
    StructField(" Idle Max", DoubleType(), True),
    StructField(" Idle Min", DoubleType(), True),
    StructField(" Label", StringType(), True),
])

CIC_IDS_2017_M_FULL_SCHEMA = StructType([
    *CIC_IDS_2017_M_SCHEMA.fields,
    StructField("day", StringType(), True),
    StructField("time_of_day", StringType(), True),
])

CIC_IDS_2017_T_SCHEMA = StructType([
    StructField("Flow ID", StringType(), True),
    StructField(" Source IP", StringType(), True),
    StructField(" Source Port", IntegerType(), True),
    StructField(" Destination IP", StringType(), True),
    StructField(" Destination Port", IntegerType(), True),
    StructField(" Protocol", IntegerType(), True),
    StructField(" Timestamp", TimestampType(), True),
    StructField(" Flow Duration", DoubleType(), True),
    StructField(" Total Fwd Packets", DoubleType(), True),
    StructField(" Total Backward Packets", DoubleType(), True),
    StructField("Total Length of Fwd Packets", DoubleType(), True),
    StructField(" Total Length of Bwd Packets", DoubleType(), True),
    StructField(" Fwd Packet Length Max", DoubleType(), True),
    StructField(" Fwd Packet Length Min", DoubleType(), True),
    StructField(" Fwd Packet Length Mean", DoubleType(), True),
    StructField(" Fwd Packet Length Std", DoubleType(), True),
    StructField("Bwd Packet Length Max", DoubleType(), True),
    StructField(" Bwd Packet Length Min", DoubleType(), True),
    StructField(" Bwd Packet Length Mean", DoubleType(), True),
    StructField(" Bwd Packet Length Std", DoubleType(), True),
    StructField("Flow Bytes/s", DoubleType(), True),
    StructField(" Flow Packets/s", DoubleType(), True),
    StructField(" Flow IAT Mean", DoubleType(), True),
    StructField(" Flow IAT Std", DoubleType(), True),
    StructField(" Flow IAT Max", DoubleType(), True),
    StructField(" Flow IAT Min", DoubleType(), True),
    StructField("Fwd IAT Total", DoubleType(), True),
    StructField(" Fwd IAT Mean", DoubleType(), True),
    StructField(" Fwd IAT Std", DoubleType(), True),
    StructField(" Fwd IAT Max", DoubleType(), True),
    StructField(" Fwd IAT Min", DoubleType(), True),
    StructField("Bwd IAT Total", DoubleType(), True),
    StructField(" Bwd IAT Mean", DoubleType(), True),
    StructField(" Bwd IAT Std", DoubleType(), True),
    StructField(" Bwd IAT Max", DoubleType(), True),
    StructField(" Bwd IAT Min", DoubleType(), True),
    StructField("Fwd PSH Flags", DoubleType(), True),
    StructField(" Bwd PSH Flags", DoubleType(), True),
    StructField(" Fwd URG Flags", DoubleType(), True),
    StructField(" Bwd URG Flags", DoubleType(), True),
    StructField(" Fwd Header Length", DoubleType(), True),
    StructField(" Bwd Header Length", DoubleType(), True),
    StructField("Fwd Packets/s", DoubleType(), True),
    StructField(" Bwd Packets/s", DoubleType(), True),
    StructField(" Min Packet Length", DoubleType(), True),
    StructField(" Max Packet Length", DoubleType(), True),
    StructField(" Packet Length Mean", DoubleType(), True),
    StructField(" Packet Length Std", DoubleType(), True),
    StructField(" Packet Length Variance", DoubleType(), True),
    StructField("FIN Flag Count", DoubleType(), True),
    StructField(" SYN Flag Count", DoubleType(), True),
    StructField(" RST Flag Count", DoubleType(), True),
    StructField(" PSH Flag Count", DoubleType(), True),
    StructField(" ACK Flag Count", DoubleType(), True),
    StructField(" URG Flag Count", DoubleType(), True),
    StructField(" CWE Flag Count", DoubleType(), True),
    StructField(" ECE Flag Count", DoubleType(), True),
    StructField(" Down/Up Ratio", DoubleType(), True),
    StructField(" Average Packet Size", DoubleType(), True),
    StructField(" Avg Fwd Segment Size", DoubleType(), True),
    StructField(" Avg Bwd Segment Size", DoubleType(), True),
    StructField(" Fwd Header Length.1", DoubleType(), True),
    StructField("Fwd Avg Bytes/Bulk", DoubleType(), True),
    StructField(" Fwd Avg Packets/Bulk", DoubleType(), True),
    StructField(" Fwd Avg Bulk Rate", DoubleType(), True),
    StructField(" Bwd Avg Bytes/Bulk", DoubleType(), True),
    StructField(" Bwd Avg Packets/Bulk", DoubleType(), True),
    StructField("Bwd Avg Bulk Rate", DoubleType(), True),
    StructField("Subflow Fwd Packets", DoubleType(), True),
    StructField(" Subflow Fwd Bytes", DoubleType(), True),
    StructField(" Subflow Bwd Packets", DoubleType(), True),
    StructField(" Subflow Bwd Bytes", DoubleType(), True),
    StructField("Init_Win_bytes_forward", DoubleType(), True),
    StructField(" Init_Win_bytes_backward", DoubleType(), True),
    StructField(" act_data_pkt_fwd", DoubleType(), True),
    StructField(" min_seg_size_forward", DoubleType(), True),
    StructField("Active Mean", DoubleType(), True),
    StructField(" Active Std", DoubleType(), True),
    StructField(" Active Max", DoubleType(), True),
    StructField(" Active Min", DoubleType(), True),
    StructField("Idle Mean", DoubleType(), True),
    StructField(" Idle Std", DoubleType(), True),
    StructField(" Idle Max", DoubleType(), True),
    StructField(" Idle Min", DoubleType(), True),
    StructField(" Label", StringType(), True),
])

CIC_IDS_2017_T_FULL_SCHEMA = StructType([
    *CIC_IDS_2017_T_SCHEMA.fields,
    StructField("day", StringType(), True),
    StructField("time_of_day", StringType(), True),
])
